# Basic dependabot.yml file with
# minimum configuration for nuget manager
version: 2
updates:
    - package-ecosystem: 'nuget'
      # Look for NuGet dependency info from the `root` directory
      directory: '/'
      schedule:
          # Check the nuget registry for updates every day (weekdays) schedule:
          interval: 'weekly'