version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        depends_on: [postgres_image]
        environment:
            - ASPNETCORE_URLS=http://+:3500
            - ASPNETCORE_ENVIRONMENT=Development
            - PostgreSQL__ConnectionString='server=localhost;port=5432;userid=postgres_user;database=eventsDb;Password=4y7sV96vA9wv46VR'
        # ports:
        #     - '8080:80'
        ports:
            - "3800:3500"
        networks:
            - events-dev

    postgres_image:
        container_name: 'postgres'
        image: postgres:latest
        environment:
            # change this for a "real" app!
            POSTGRES_PASSWORD: '4y7sV96vA9wv46VR'
            POSTGRES_USER: 'postgres_user'
            POSTGES_DB: 'eventsDb'
            PGDATA: /data/postgres
        restart: always
        volumes:
            - postgres:/data/postgres
        networks:
            - events-dev
        ports:
            - 5432:5432

    nginx:
        build: 
            context: ../../nginx
        ports:
        - "3000:80"

volumes:
    postgres:

networks:
    events-dev:
        driver: bridge