name: Docker Image CI

on:
    push:
        branches: [main]
    # pull_request:
    #   branches: [ main ]
    workflow_dispatch:

env:
    DOTNET_VERSION: '6.0.x' # set this to the dot net version to use

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src/EventsAPI
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag git_docker:$(date +%s)

            # - uses: docker/login-action@v1
            # - name: Login to Docker Hub
            #   with:
            #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
            #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
